name: Docker Container
run-name: ${{ github.actor }} is building the docker image 🚀

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the repository
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name:  Build and push full version
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lyx:${{ github.event.release.tag_name}}
      -
        name: Build and push minimal version
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-minimal
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lyx:minimal-${{ github.event.release.tag_name }}